# Generated by Django 3.1.7 on 2021-03-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20210310_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/media/profile_pics/no_profile_pic/moving_boxes_Hft6TBm.jpg', upload_to='profile_pics'),
        ),
    ]
