# Generated by Django 3.1.7 on 2021-03-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20210311_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/images/media/profile_pics/no_profile_pic/moving_boxes_Hft6TBm.jpg', upload_to='profile_pics'),
        ),
    ]
