# Generated by Django 3.1.7 on 2021-03-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_auto_20210312_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo_picture',
            name='cargo_picture',
            field=models.ImageField(blank=True, upload_to='cargo_pictures'),
        ),
    ]
