# Generated by Django 3.1.7 on 2021-03-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/no_profile_pic/no_pp.jpg', upload_to='profile_pics'),
        ),
    ]
