# Generated by Django 3.1.7 on 2021-03-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/no_profile_pic/no_pp.png', upload_to='profile_pics'),
        ),
    ]
