# Generated by Django 3.1.7 on 2021-03-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20210311_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/no_profile_pic/moving_boxes_Hft6TBm.jpg', upload_to='profile_pics'),
        ),
    ]
